[package]
name = "game_mode"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = "4.0"
toml = "0.5.8"
colored = "2.0.0"
clap = { version = "3.1.12", features = ["derive"] }
ctrlc = "3.2.1"
